import Head from 'next/head'
import '@/i18next';
import i18n from '@/i18next';
import { useTranslation} from 'react-i18next'
import Dashboard from './dashboard'

export default function Home() {
  const {t} = useTranslation()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

      <Dashboard />
      
      </main>
      <h1 className='text-[50px] text-center'> 
      {t('hello')} 
      </h1>
      <div className='flex justify-center'>
      <select value={i18n.language} onChange={(e) => {
     i18n.changeLanguage(e.target.value)
      }}
      className='border-b-2 border-blue-600'>
        <option value="fa">Persian</option>
        <option value="en">English</option>
      </select>
      </div>

    </>
  )
}
